name: flutter_custom_tabs
description: Flutter plugin for seamlessly displaying web content using Chrome Custom Tabs.
version: 0.7.0
homepage: https://github.com/droibit/flutter_custom_tabs

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  # TODO: Depends on the package on pub.dev
  flutter_custom_tabs_platform_interface:
    path: ../flutter_custom_tabs_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.9
  pedantic: ^1.11.0
  plugin_platform_interface: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.github.droibit.flutter.plugins.customtabs
        pluginClass: CustomTabsPlugin
      ios:
        pluginClass: GDBCustomTabsPlugin